// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/types/testing_types.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TechniqueItemType int32

const (
	TechniqueItemType_TECHNIQUE_ITEM_TYPE_UNSPECIFIED                          TechniqueItemType = 0
	TechniqueItemType_TECHNIQUE_ITEM_TYPE_QUESTION_WITH_VARIANTS_SINGLE_ANSWER TechniqueItemType = 1
)

// Enum value maps for TechniqueItemType.
var (
	TechniqueItemType_name = map[int32]string{
		0: "TECHNIQUE_ITEM_TYPE_UNSPECIFIED",
		1: "TECHNIQUE_ITEM_TYPE_QUESTION_WITH_VARIANTS_SINGLE_ANSWER",
	}
	TechniqueItemType_value = map[string]int32{
		"TECHNIQUE_ITEM_TYPE_UNSPECIFIED":                          0,
		"TECHNIQUE_ITEM_TYPE_QUESTION_WITH_VARIANTS_SINGLE_ANSWER": 1,
	}
)

func (x TechniqueItemType) Enum() *TechniqueItemType {
	p := new(TechniqueItemType)
	*p = x
	return p
}

func (x TechniqueItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TechniqueItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_testing_types_proto_enumTypes[0].Descriptor()
}

func (TechniqueItemType) Type() protoreflect.EnumType {
	return &file_common_types_testing_types_proto_enumTypes[0]
}

func (x TechniqueItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TechniqueItemType.Descriptor instead.
func (TechniqueItemType) EnumDescriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{0}
}

type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_UNSPECIFIED RoomStatus = 0
	RoomStatus_ROOM_STATUS_NOT_STARTED RoomStatus = 1
	RoomStatus_ROOM_STATUS_FINISHED    RoomStatus = 10
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0:  "ROOM_STATUS_UNSPECIFIED",
		1:  "ROOM_STATUS_NOT_STARTED",
		10: "ROOM_STATUS_FINISHED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_UNSPECIFIED": 0,
		"ROOM_STATUS_NOT_STARTED": 1,
		"ROOM_STATUS_FINISHED":    10,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_testing_types_proto_enumTypes[1].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_common_types_testing_types_proto_enumTypes[1]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{1}
}

type PersonalityTraitType int32

const (
	PersonalityTraitType_PERSONALITY_TRAIT_TYPE_UNSPECIFIED PersonalityTraitType = 0
	PersonalityTraitType_PERSONALITY_TRAIT_TYPE_BIPOLAR     PersonalityTraitType = 1
)

// Enum value maps for PersonalityTraitType.
var (
	PersonalityTraitType_name = map[int32]string{
		0: "PERSONALITY_TRAIT_TYPE_UNSPECIFIED",
		1: "PERSONALITY_TRAIT_TYPE_BIPOLAR",
	}
	PersonalityTraitType_value = map[string]int32{
		"PERSONALITY_TRAIT_TYPE_UNSPECIFIED": 0,
		"PERSONALITY_TRAIT_TYPE_BIPOLAR":     1,
	}
)

func (x PersonalityTraitType) Enum() *PersonalityTraitType {
	p := new(PersonalityTraitType)
	*p = x
	return p
}

func (x PersonalityTraitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonalityTraitType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_testing_types_proto_enumTypes[2].Descriptor()
}

func (PersonalityTraitType) Type() protoreflect.EnumType {
	return &file_common_types_testing_types_proto_enumTypes[2]
}

func (x PersonalityTraitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonalityTraitType.Descriptor instead.
func (PersonalityTraitType) EnumDescriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{2}
}

type PersonalityTraitPriority int32

const (
	PersonalityTraitPriority_PRESONALITY_TRAIT_PRIORITY_NONE   PersonalityTraitPriority = 0
	PersonalityTraitPriority_PRESONALITY_TRAIT_PRIORITY_LOW    PersonalityTraitPriority = 1
	PersonalityTraitPriority_PRESONALITY_TRAIT_PRIORITY_MEDIUM PersonalityTraitPriority = 2
	PersonalityTraitPriority_PRESONALITY_TRAIT_PRIORITY_HIGH   PersonalityTraitPriority = 3
)

// Enum value maps for PersonalityTraitPriority.
var (
	PersonalityTraitPriority_name = map[int32]string{
		0: "PRESONALITY_TRAIT_PRIORITY_NONE",
		1: "PRESONALITY_TRAIT_PRIORITY_LOW",
		2: "PRESONALITY_TRAIT_PRIORITY_MEDIUM",
		3: "PRESONALITY_TRAIT_PRIORITY_HIGH",
	}
	PersonalityTraitPriority_value = map[string]int32{
		"PRESONALITY_TRAIT_PRIORITY_NONE":   0,
		"PRESONALITY_TRAIT_PRIORITY_LOW":    1,
		"PRESONALITY_TRAIT_PRIORITY_MEDIUM": 2,
		"PRESONALITY_TRAIT_PRIORITY_HIGH":   3,
	}
)

func (x PersonalityTraitPriority) Enum() *PersonalityTraitPriority {
	p := new(PersonalityTraitPriority)
	*p = x
	return p
}

func (x PersonalityTraitPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonalityTraitPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_testing_types_proto_enumTypes[3].Descriptor()
}

func (PersonalityTraitPriority) Type() protoreflect.EnumType {
	return &file_common_types_testing_types_proto_enumTypes[3]
}

func (x PersonalityTraitPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonalityTraitPriority.Descriptor instead.
func (PersonalityTraitPriority) EnumDescriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{3}
}

type PersonalityTrait struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           PersonalityTraitType   `protobuf:"varint,2,opt,name=type,proto3,enum=types.v1.PersonalityTraitType" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LeftStateName  string                 `protobuf:"bytes,5,opt,name=left_state_name,json=leftStateName,proto3" json:"left_state_name,omitempty"`
	RightStateName string                 `protobuf:"bytes,6,opt,name=right_state_name,json=rightStateName,proto3" json:"right_state_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersonalityTrait) Reset() {
	*x = PersonalityTrait{}
	mi := &file_common_types_testing_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalityTrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalityTrait) ProtoMessage() {}

func (x *PersonalityTrait) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalityTrait.ProtoReflect.Descriptor instead.
func (*PersonalityTrait) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalityTrait) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonalityTrait) GetType() PersonalityTraitType {
	if x != nil {
		return x.Type
	}
	return PersonalityTraitType_PERSONALITY_TRAIT_TYPE_UNSPECIFIED
}

func (x *PersonalityTrait) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalityTrait) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PersonalityTrait) GetLeftStateName() string {
	if x != nil {
		return x.LeftStateName
	}
	return ""
}

func (x *PersonalityTrait) GetRightStateName() string {
	if x != nil {
		return x.RightStateName
	}
	return ""
}

type ProfilePersonalityTraitsMapItem struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Priority      PersonalityTraitPriority `protobuf:"varint,1,opt,name=priority,proto3,enum=types.v1.PersonalityTraitPriority" json:"priority,omitempty"`
	Target        int32                    `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilePersonalityTraitsMapItem) Reset() {
	*x = ProfilePersonalityTraitsMapItem{}
	mi := &file_common_types_testing_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilePersonalityTraitsMapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePersonalityTraitsMapItem) ProtoMessage() {}

func (x *ProfilePersonalityTraitsMapItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePersonalityTraitsMapItem.ProtoReflect.Descriptor instead.
func (*ProfilePersonalityTraitsMapItem) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{1}
}

func (x *ProfilePersonalityTraitsMapItem) GetPriority() PersonalityTraitPriority {
	if x != nil {
		return x.Priority
	}
	return PersonalityTraitPriority_PRESONALITY_TRAIT_PRIORITY_NONE
}

func (x *ProfilePersonalityTraitsMapItem) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

type ProfilePersonalityTraitsMap struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Map           map[uint64]*ProfilePersonalityTraitsMapItem `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilePersonalityTraitsMap) Reset() {
	*x = ProfilePersonalityTraitsMap{}
	mi := &file_common_types_testing_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilePersonalityTraitsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePersonalityTraitsMap) ProtoMessage() {}

func (x *ProfilePersonalityTraitsMap) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePersonalityTraitsMap.ProtoReflect.Descriptor instead.
func (*ProfilePersonalityTraitsMap) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{2}
}

func (x *ProfilePersonalityTraitsMap) GetMap() map[uint64]*ProfilePersonalityTraitsMapItem {
	if x != nil {
		return x.Map
	}
	return nil
}

type TestingProfile struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Id                string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version           int64                        `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TenantId          string                       `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name              string                       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PersonalityTraits *ProfilePersonalityTraitsMap `protobuf:"bytes,6,opt,name=personality_traits,json=personalityTraits,proto3" json:"personality_traits,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TestingProfile) Reset() {
	*x = TestingProfile{}
	mi := &file_common_types_testing_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingProfile) ProtoMessage() {}

func (x *TestingProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingProfile.ProtoReflect.Descriptor instead.
func (*TestingProfile) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{3}
}

func (x *TestingProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestingProfile) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TestingProfile) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TestingProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestingProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TestingProfile) GetPersonalityTraits() *ProfilePersonalityTraitsMap {
	if x != nil {
		return x.PersonalityTraits
	}
	return nil
}

type TestingListProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestingListProfile) Reset() {
	*x = TestingListProfile{}
	mi := &file_common_types_testing_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingListProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingListProfile) ProtoMessage() {}

func (x *TestingListProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingListProfile.ProtoReflect.Descriptor instead.
func (*TestingListProfile) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{4}
}

func (x *TestingListProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestingListProfile) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TestingListProfile) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TestingListProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TestingRoomCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestingRoomCandidate) Reset() {
	*x = TestingRoomCandidate{}
	mi := &file_common_types_testing_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingRoomCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRoomCandidate) ProtoMessage() {}

func (x *TestingRoomCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingRoomCandidate.ProtoReflect.Descriptor instead.
func (*TestingRoomCandidate) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{5}
}

func (x *TestingRoomCandidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestingRoomCandidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestingRoomCandidate) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type TestingRoomProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestingRoomProfile) Reset() {
	*x = TestingRoomProfile{}
	mi := &file_common_types_testing_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingRoomProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRoomProfile) ProtoMessage() {}

func (x *TestingRoomProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingRoomProfile.ProtoReflect.Descriptor instead.
func (*TestingRoomProfile) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{6}
}

func (x *TestingRoomProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestingRoomProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TestingRoomResultTrait struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         float32                `protobuf:"fixed32,1,opt,name=match,proto3" json:"match,omitempty"`
	Tip           string                 `protobuf:"bytes,2,opt,name=tip,proto3" json:"tip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestingRoomResultTrait) Reset() {
	*x = TestingRoomResultTrait{}
	mi := &file_common_types_testing_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingRoomResultTrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRoomResultTrait) ProtoMessage() {}

func (x *TestingRoomResultTrait) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingRoomResultTrait.ProtoReflect.Descriptor instead.
func (*TestingRoomResultTrait) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{7}
}

func (x *TestingRoomResultTrait) GetMatch() float32 {
	if x != nil {
		return x.Match
	}
	return 0
}

func (x *TestingRoomResultTrait) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

type TestingRoomResult struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	TotalMatch    float32                            `protobuf:"fixed32,1,opt,name=total_match,json=totalMatch,proto3" json:"total_match,omitempty"`
	TotalMatchTip string                             `protobuf:"bytes,2,opt,name=total_match_tip,json=totalMatchTip,proto3" json:"total_match_tip,omitempty"`
	Traits        map[uint64]*TestingRoomResultTrait `protobuf:"bytes,3,rep,name=traits,proto3" json:"traits,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestingRoomResult) Reset() {
	*x = TestingRoomResult{}
	mi := &file_common_types_testing_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingRoomResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRoomResult) ProtoMessage() {}

func (x *TestingRoomResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingRoomResult.ProtoReflect.Descriptor instead.
func (*TestingRoomResult) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{8}
}

func (x *TestingRoomResult) GetTotalMatch() float32 {
	if x != nil {
		return x.TotalMatch
	}
	return 0
}

func (x *TestingRoomResult) GetTotalMatchTip() string {
	if x != nil {
		return x.TotalMatchTip
	}
	return ""
}

func (x *TestingRoomResult) GetTraits() map[uint64]*TestingRoomResultTrait {
	if x != nil {
		return x.Traits
	}
	return nil
}

type TestingRoom struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Id                string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version           int64                        `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TenantId          string                       `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status            RoomStatus                   `protobuf:"varint,4,opt,name=status,proto3,enum=types.v1.RoomStatus" json:"status,omitempty"`
	Candidate         *TestingRoomCandidate        `protobuf:"bytes,5,opt,name=candidate,proto3,oneof" json:"candidate,omitempty"`
	Profile           *TestingRoomProfile          `protobuf:"bytes,6,opt,name=profile,proto3,oneof" json:"profile,omitempty"`
	Result            *TestingRoomResult           `protobuf:"bytes,7,opt,name=result,proto3,oneof" json:"result,omitempty"`
	PersonalityTraits *ProfilePersonalityTraitsMap `protobuf:"bytes,8,opt,name=personality_traits,json=personalityTraits,proto3" json:"personality_traits,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TestingRoom) Reset() {
	*x = TestingRoom{}
	mi := &file_common_types_testing_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRoom) ProtoMessage() {}

func (x *TestingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingRoom.ProtoReflect.Descriptor instead.
func (*TestingRoom) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{9}
}

func (x *TestingRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestingRoom) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TestingRoom) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TestingRoom) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *TestingRoom) GetCandidate() *TestingRoomCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *TestingRoom) GetProfile() *TestingRoomProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *TestingRoom) GetResult() *TestingRoomResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TestingRoom) GetPersonalityTraits() *ProfilePersonalityTraitsMap {
	if x != nil {
		return x.PersonalityTraits
	}
	return nil
}

type TestingListRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        RoomStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=types.v1.RoomStatus" json:"status,omitempty"`
	Candidate     *TestingRoomCandidate  `protobuf:"bytes,5,opt,name=candidate,proto3,oneof" json:"candidate,omitempty"`
	Profile       *TestingRoomProfile    `protobuf:"bytes,6,opt,name=profile,proto3,oneof" json:"profile,omitempty"`
	Result        *TestingRoomResult     `protobuf:"bytes,7,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestingListRoom) Reset() {
	*x = TestingListRoom{}
	mi := &file_common_types_testing_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingListRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingListRoom) ProtoMessage() {}

func (x *TestingListRoom) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_testing_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingListRoom.ProtoReflect.Descriptor instead.
func (*TestingListRoom) Descriptor() ([]byte, []int) {
	return file_common_types_testing_types_proto_rawDescGZIP(), []int{10}
}

func (x *TestingListRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestingListRoom) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TestingListRoom) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TestingListRoom) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *TestingListRoom) GetCandidate() *TestingRoomCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *TestingListRoom) GetProfile() *TestingRoomProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *TestingListRoom) GetResult() *TestingRoomResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_common_types_testing_types_proto protoreflect.FileDescriptor

const file_common_types_testing_types_proto_rawDesc = "" +
	"\n" +
	" common/types/testing_types.proto\x12\btypes.v1\"\xde\x01\n" +
	"\x10PersonalityTrait\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.types.v1.PersonalityTraitTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fleft_state_name\x18\x05 \x01(\tR\rleftStateName\x12(\n" +
	"\x10right_state_name\x18\x06 \x01(\tR\x0erightStateName\"y\n" +
	"\x1fProfilePersonalityTraitsMapItem\x12>\n" +
	"\bpriority\x18\x01 \x01(\x0e2\".types.v1.PersonalityTraitPriorityR\bpriority\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\"\xc2\x01\n" +
	"\x1bProfilePersonalityTraitsMap\x12@\n" +
	"\x03map\x18\x01 \x03(\v2..types.v1.ProfilePersonalityTraitsMap.MapEntryR\x03map\x1aa\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12?\n" +
	"\x05value\x18\x02 \x01(\v2).types.v1.ProfilePersonalityTraitsMapItemR\x05value:\x028\x01\"\xe3\x01\n" +
	"\x0eTestingProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12T\n" +
	"\x12personality_traits\x18\x06 \x01(\v2%.types.v1.ProfilePersonalityTraitsMapR\x11personalityTraits\"o\n" +
	"\x12TestingListProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"T\n" +
	"\x14TestingRoomCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\"8\n" +
	"\x12TestingRoomProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x16TestingRoomResultTrait\x12\x14\n" +
	"\x05match\x18\x01 \x01(\x02R\x05match\x12\x10\n" +
	"\x03tip\x18\x02 \x01(\tR\x03tip\"\xfa\x01\n" +
	"\x11TestingRoomResult\x12\x1f\n" +
	"\vtotal_match\x18\x01 \x01(\x02R\n" +
	"totalMatch\x12&\n" +
	"\x0ftotal_match_tip\x18\x02 \x01(\tR\rtotalMatchTip\x12?\n" +
	"\x06traits\x18\x03 \x03(\v2'.types.v1.TestingRoomResult.TraitsEntryR\x06traits\x1a[\n" +
	"\vTraitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .types.v1.TestingRoomResultTraitR\x05value:\x028\x01\"\xb7\x03\n" +
	"\vTestingRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.types.v1.RoomStatusR\x06status\x12A\n" +
	"\tcandidate\x18\x05 \x01(\v2\x1e.types.v1.TestingRoomCandidateH\x00R\tcandidate\x88\x01\x01\x12;\n" +
	"\aprofile\x18\x06 \x01(\v2\x1c.types.v1.TestingRoomProfileH\x01R\aprofile\x88\x01\x01\x128\n" +
	"\x06result\x18\a \x01(\v2\x1b.types.v1.TestingRoomResultH\x02R\x06result\x88\x01\x01\x12T\n" +
	"\x12personality_traits\x18\b \x01(\v2%.types.v1.ProfilePersonalityTraitsMapR\x11personalityTraitsB\f\n" +
	"\n" +
	"_candidateB\n" +
	"\n" +
	"\b_profileB\t\n" +
	"\a_result\"\xe5\x02\n" +
	"\x0fTestingListRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.types.v1.RoomStatusR\x06status\x12A\n" +
	"\tcandidate\x18\x05 \x01(\v2\x1e.types.v1.TestingRoomCandidateH\x00R\tcandidate\x88\x01\x01\x12;\n" +
	"\aprofile\x18\x06 \x01(\v2\x1c.types.v1.TestingRoomProfileH\x01R\aprofile\x88\x01\x01\x128\n" +
	"\x06result\x18\a \x01(\v2\x1b.types.v1.TestingRoomResultH\x02R\x06result\x88\x01\x01B\f\n" +
	"\n" +
	"_candidateB\n" +
	"\n" +
	"\b_profileB\t\n" +
	"\a_result*v\n" +
	"\x11TechniqueItemType\x12#\n" +
	"\x1fTECHNIQUE_ITEM_TYPE_UNSPECIFIED\x10\x00\x12<\n" +
	"8TECHNIQUE_ITEM_TYPE_QUESTION_WITH_VARIANTS_SINGLE_ANSWER\x10\x01*`\n" +
	"\n" +
	"RoomStatus\x12\x1b\n" +
	"\x17ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ROOM_STATUS_NOT_STARTED\x10\x01\x12\x18\n" +
	"\x14ROOM_STATUS_FINISHED\x10\n" +
	"*b\n" +
	"\x14PersonalityTraitType\x12&\n" +
	"\"PERSONALITY_TRAIT_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1ePERSONALITY_TRAIT_TYPE_BIPOLAR\x10\x01*\xaf\x01\n" +
	"\x18PersonalityTraitPriority\x12#\n" +
	"\x1fPRESONALITY_TRAIT_PRIORITY_NONE\x10\x00\x12\"\n" +
	"\x1ePRESONALITY_TRAIT_PRIORITY_LOW\x10\x01\x12%\n" +
	"!PRESONALITY_TRAIT_PRIORITY_MEDIUM\x10\x02\x12#\n" +
	"\x1fPRESONALITY_TRAIT_PRIORITY_HIGH\x10\x03B\xa2\x01\n" +
	"\fcom.types.v1B\x11TestingTypesProtoP\x01Z>github.com/neurochar/backend/pkg/proto_pb/common/types;typesv1\xa2\x02\x03TXX\xaa\x02\bTypes.V1\xca\x02\bTypes\\V1\xe2\x02\x14Types\\V1\\GPBMetadata\xea\x02\tTypes::V1b\x06proto3"

var (
	file_common_types_testing_types_proto_rawDescOnce sync.Once
	file_common_types_testing_types_proto_rawDescData []byte
)

func file_common_types_testing_types_proto_rawDescGZIP() []byte {
	file_common_types_testing_types_proto_rawDescOnce.Do(func() {
		file_common_types_testing_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_testing_types_proto_rawDesc), len(file_common_types_testing_types_proto_rawDesc)))
	})
	return file_common_types_testing_types_proto_rawDescData
}

var file_common_types_testing_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_types_testing_types_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_common_types_testing_types_proto_goTypes = []any{
	(TechniqueItemType)(0),                  // 0: types.v1.TechniqueItemType
	(RoomStatus)(0),                         // 1: types.v1.RoomStatus
	(PersonalityTraitType)(0),               // 2: types.v1.PersonalityTraitType
	(PersonalityTraitPriority)(0),           // 3: types.v1.PersonalityTraitPriority
	(*PersonalityTrait)(nil),                // 4: types.v1.PersonalityTrait
	(*ProfilePersonalityTraitsMapItem)(nil), // 5: types.v1.ProfilePersonalityTraitsMapItem
	(*ProfilePersonalityTraitsMap)(nil),     // 6: types.v1.ProfilePersonalityTraitsMap
	(*TestingProfile)(nil),                  // 7: types.v1.TestingProfile
	(*TestingListProfile)(nil),              // 8: types.v1.TestingListProfile
	(*TestingRoomCandidate)(nil),            // 9: types.v1.TestingRoomCandidate
	(*TestingRoomProfile)(nil),              // 10: types.v1.TestingRoomProfile
	(*TestingRoomResultTrait)(nil),          // 11: types.v1.TestingRoomResultTrait
	(*TestingRoomResult)(nil),               // 12: types.v1.TestingRoomResult
	(*TestingRoom)(nil),                     // 13: types.v1.TestingRoom
	(*TestingListRoom)(nil),                 // 14: types.v1.TestingListRoom
	nil,                                     // 15: types.v1.ProfilePersonalityTraitsMap.MapEntry
	nil,                                     // 16: types.v1.TestingRoomResult.TraitsEntry
}
var file_common_types_testing_types_proto_depIdxs = []int32{
	2,  // 0: types.v1.PersonalityTrait.type:type_name -> types.v1.PersonalityTraitType
	3,  // 1: types.v1.ProfilePersonalityTraitsMapItem.priority:type_name -> types.v1.PersonalityTraitPriority
	15, // 2: types.v1.ProfilePersonalityTraitsMap.map:type_name -> types.v1.ProfilePersonalityTraitsMap.MapEntry
	6,  // 3: types.v1.TestingProfile.personality_traits:type_name -> types.v1.ProfilePersonalityTraitsMap
	16, // 4: types.v1.TestingRoomResult.traits:type_name -> types.v1.TestingRoomResult.TraitsEntry
	1,  // 5: types.v1.TestingRoom.status:type_name -> types.v1.RoomStatus
	9,  // 6: types.v1.TestingRoom.candidate:type_name -> types.v1.TestingRoomCandidate
	10, // 7: types.v1.TestingRoom.profile:type_name -> types.v1.TestingRoomProfile
	12, // 8: types.v1.TestingRoom.result:type_name -> types.v1.TestingRoomResult
	6,  // 9: types.v1.TestingRoom.personality_traits:type_name -> types.v1.ProfilePersonalityTraitsMap
	1,  // 10: types.v1.TestingListRoom.status:type_name -> types.v1.RoomStatus
	9,  // 11: types.v1.TestingListRoom.candidate:type_name -> types.v1.TestingRoomCandidate
	10, // 12: types.v1.TestingListRoom.profile:type_name -> types.v1.TestingRoomProfile
	12, // 13: types.v1.TestingListRoom.result:type_name -> types.v1.TestingRoomResult
	5,  // 14: types.v1.ProfilePersonalityTraitsMap.MapEntry.value:type_name -> types.v1.ProfilePersonalityTraitsMapItem
	11, // 15: types.v1.TestingRoomResult.TraitsEntry.value:type_name -> types.v1.TestingRoomResultTrait
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_common_types_testing_types_proto_init() }
func file_common_types_testing_types_proto_init() {
	if File_common_types_testing_types_proto != nil {
		return
	}
	file_common_types_testing_types_proto_msgTypes[9].OneofWrappers = []any{}
	file_common_types_testing_types_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_testing_types_proto_rawDesc), len(file_common_types_testing_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_testing_types_proto_goTypes,
		DependencyIndexes: file_common_types_testing_types_proto_depIdxs,
		EnumInfos:         file_common_types_testing_types_proto_enumTypes,
		MessageInfos:      file_common_types_testing_types_proto_msgTypes,
	}.Build()
	File_common_types_testing_types_proto = out.File
	file_common_types_testing_types_proto_goTypes = nil
	file_common_types_testing_types_proto_depIdxs = nil
}
