// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/crm/v1/service.proto

package crmv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_crm_v1_service_proto protoreflect.FileDescriptor

const file_public_crm_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bpublic/crm/v1/service.proto\x12\x06crm.v1\x1a\x17public/crm/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xa9\x06\n" +
	"\x16CrmTenantPublicService\x12r\n" +
	"\x0eListCandidates\x12\x1d.crm.v1.ListCandidatesRequest\x1a\x1e.crm.v1.ListCandidatesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/tenant/crm/candidates\x12q\n" +
	"\fGetCandidate\x12\x1b.crm.v1.GetCandidateRequest\x1a\x1c.crm.v1.GetCandidateResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/tenant/crm/candidates/{id}\x12x\n" +
	"\x0fCreateCandidate\x12\x1e.crm.v1.CreateCandidateRequest\x1a\x1f.crm.v1.CreateCandidateResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/tenant/crm/candidates\x12z\n" +
	"\x0ePatchCandidate\x12\x1d.crm.v1.PatchCandidateRequest\x1a\x1e.crm.v1.PatchCandidateResponse\")\x82\xd3\xe4\x93\x02#:\x01*2\x1e/v1/tenant/crm/candidates/{id}\x12z\n" +
	"\x0fDeleteCandidate\x12\x1e.crm.v1.DeleteCandidateRequest\x1a\x1f.crm.v1.DeleteCandidateResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/v1/tenant/crm/candidates/{id}\x12\xb5\x01\n" +
	"\x19UploadCandidateResumeFile\x12(.crm.v1.UploadCandidateResumeFileRequest\x1a).crm.v1.UploadCandidateResumeFileResponse\"C\x92A\x152\x13multipart/form-data\x82\xd3\xe4\x93\x02%:\x01*\" /v1/tenant/crm/candidates-resumeB\x92\x01\n" +
	"\n" +
	"com.crm.v1B\fServiceProtoP\x01Z=github.com/neurochar/backend/pkg/proto_pb/public/crm/v1;crmv1\xa2\x02\x03CXX\xaa\x02\x06Crm.V1\xca\x02\x06Crm\\V1\xe2\x02\x12Crm\\V1\\GPBMetadata\xea\x02\aCrm::V1b\x06proto3"

var file_public_crm_v1_service_proto_goTypes = []any{
	(*ListCandidatesRequest)(nil),             // 0: crm.v1.ListCandidatesRequest
	(*GetCandidateRequest)(nil),               // 1: crm.v1.GetCandidateRequest
	(*CreateCandidateRequest)(nil),            // 2: crm.v1.CreateCandidateRequest
	(*PatchCandidateRequest)(nil),             // 3: crm.v1.PatchCandidateRequest
	(*DeleteCandidateRequest)(nil),            // 4: crm.v1.DeleteCandidateRequest
	(*UploadCandidateResumeFileRequest)(nil),  // 5: crm.v1.UploadCandidateResumeFileRequest
	(*ListCandidatesResponse)(nil),            // 6: crm.v1.ListCandidatesResponse
	(*GetCandidateResponse)(nil),              // 7: crm.v1.GetCandidateResponse
	(*CreateCandidateResponse)(nil),           // 8: crm.v1.CreateCandidateResponse
	(*PatchCandidateResponse)(nil),            // 9: crm.v1.PatchCandidateResponse
	(*DeleteCandidateResponse)(nil),           // 10: crm.v1.DeleteCandidateResponse
	(*UploadCandidateResumeFileResponse)(nil), // 11: crm.v1.UploadCandidateResumeFileResponse
}
var file_public_crm_v1_service_proto_depIdxs = []int32{
	0,  // 0: crm.v1.CrmTenantPublicService.ListCandidates:input_type -> crm.v1.ListCandidatesRequest
	1,  // 1: crm.v1.CrmTenantPublicService.GetCandidate:input_type -> crm.v1.GetCandidateRequest
	2,  // 2: crm.v1.CrmTenantPublicService.CreateCandidate:input_type -> crm.v1.CreateCandidateRequest
	3,  // 3: crm.v1.CrmTenantPublicService.PatchCandidate:input_type -> crm.v1.PatchCandidateRequest
	4,  // 4: crm.v1.CrmTenantPublicService.DeleteCandidate:input_type -> crm.v1.DeleteCandidateRequest
	5,  // 5: crm.v1.CrmTenantPublicService.UploadCandidateResumeFile:input_type -> crm.v1.UploadCandidateResumeFileRequest
	6,  // 6: crm.v1.CrmTenantPublicService.ListCandidates:output_type -> crm.v1.ListCandidatesResponse
	7,  // 7: crm.v1.CrmTenantPublicService.GetCandidate:output_type -> crm.v1.GetCandidateResponse
	8,  // 8: crm.v1.CrmTenantPublicService.CreateCandidate:output_type -> crm.v1.CreateCandidateResponse
	9,  // 9: crm.v1.CrmTenantPublicService.PatchCandidate:output_type -> crm.v1.PatchCandidateResponse
	10, // 10: crm.v1.CrmTenantPublicService.DeleteCandidate:output_type -> crm.v1.DeleteCandidateResponse
	11, // 11: crm.v1.CrmTenantPublicService.UploadCandidateResumeFile:output_type -> crm.v1.UploadCandidateResumeFileResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_public_crm_v1_service_proto_init() }
func file_public_crm_v1_service_proto_init() {
	if File_public_crm_v1_service_proto != nil {
		return
	}
	file_public_crm_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_crm_v1_service_proto_rawDesc), len(file_public_crm_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_crm_v1_service_proto_goTypes,
		DependencyIndexes: file_public_crm_v1_service_proto_depIdxs,
	}.Build()
	File_public_crm_v1_service_proto = out.File
	file_public_crm_v1_service_proto_goTypes = nil
	file_public_crm_v1_service_proto_depIdxs = nil
}
