// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/rooms/v1/dto.proto

package roomsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	types "github.com/neurochar/backend/pkg/proto_pb/common/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateName string                 `protobuf:"bytes,1,opt,name=candidate_name,json=candidateName,proto3" json:"candidate_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCandidate) Reset() {
	*x = RoomCandidate{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCandidate) ProtoMessage() {}

func (x *RoomCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCandidate.ProtoReflect.Descriptor instead.
func (*RoomCandidate) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{0}
}

func (x *RoomCandidate) GetCandidateName() string {
	if x != nil {
		return x.CandidateName
	}
	return ""
}

type RoomTechniqueItem struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          types.TechniqueItemType `protobuf:"varint,1,opt,name=type,proto3,enum=types.v1.TechniqueItemType" json:"type,omitempty"`
	Question      string                  `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Variants      []string                `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomTechniqueItem) Reset() {
	*x = RoomTechniqueItem{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomTechniqueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTechniqueItem) ProtoMessage() {}

func (x *RoomTechniqueItem) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTechniqueItem.ProtoReflect.Descriptor instead.
func (*RoomTechniqueItem) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{1}
}

func (x *RoomTechniqueItem) GetType() types.TechniqueItemType {
	if x != nil {
		return x.Type
	}
	return types.TechniqueItemType(0)
}

func (x *RoomTechniqueItem) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *RoomTechniqueItem) GetVariants() []string {
	if x != nil {
		return x.Variants
	}
	return nil
}

type Room struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               types.RoomStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=types.v1.RoomStatus" json:"status,omitempty"`
	TenantName           string                 `protobuf:"bytes,3,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Candidate            *RoomCandidate         `protobuf:"bytes,4,opt,name=candidate,proto3" json:"candidate,omitempty"`
	CurrentQuestion      *RoomTechniqueItem     `protobuf:"bytes,5,opt,name=current_question,json=currentQuestion,proto3" json:"current_question,omitempty"`
	CurrentQuestionIndex *int32                 `protobuf:"varint,6,opt,name=current_question_index,json=currentQuestionIndex,proto3,oneof" json:"current_question_index,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetStatus() types.RoomStatus {
	if x != nil {
		return x.Status
	}
	return types.RoomStatus(0)
}

func (x *Room) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *Room) GetCandidate() *RoomCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *Room) GetCurrentQuestion() *RoomTechniqueItem {
	if x != nil {
		return x.CurrentQuestion
	}
	return nil
}

func (x *Room) GetCurrentQuestionIndex() int32 {
	if x != nil && x.CurrentQuestionIndex != nil {
		return *x.CurrentQuestionIndex
	}
	return 0
}

type AnswerValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnswerValue_StringValue
	//	*AnswerValue_IntValue
	//	*AnswerValue_DoubleValue
	//	*AnswerValue_BoolValue
	Value         isAnswerValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerValue) Reset() {
	*x = AnswerValue{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerValue) ProtoMessage() {}

func (x *AnswerValue) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerValue.ProtoReflect.Descriptor instead.
func (*AnswerValue) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{3}
}

func (x *AnswerValue) GetValue() isAnswerValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnswerValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnswerValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnswerValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnswerValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnswerValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnswerValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AnswerValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnswerValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isAnswerValue_Value interface {
	isAnswerValue_Value()
}

type AnswerValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnswerValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnswerValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AnswerValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*AnswerValue_StringValue) isAnswerValue_Value() {}

func (*AnswerValue_IntValue) isAnswerValue_Value() {}

func (*AnswerValue_DoubleValue) isAnswerValue_Value() {}

func (*AnswerValue_BoolValue) isAnswerValue_Value() {}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type StartRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoomRequest) Reset() {
	*x = StartRoomRequest{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoomRequest) ProtoMessage() {}

func (x *StartRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoomRequest.ProtoReflect.Descriptor instead.
func (*StartRoomRequest) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{6}
}

func (x *StartRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoomResponse) Reset() {
	*x = StartRoomResponse{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoomResponse) ProtoMessage() {}

func (x *StartRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoomResponse.ProtoReflect.Descriptor instead.
func (*StartRoomResponse) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{7}
}

func (x *StartRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionIndex int32                  `protobuf:"varint,2,opt,name=question_index,json=questionIndex,proto3" json:"question_index,omitempty"`
	AnswerValue   *AnswerValue           `protobuf:"bytes,3,opt,name=answer_value,json=answerValue,proto3" json:"answer_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{8}
}

func (x *AnswerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnswerRequest) GetQuestionIndex() int32 {
	if x != nil {
		return x.QuestionIndex
	}
	return 0
}

func (x *AnswerRequest) GetAnswerValue() *AnswerValue {
	if x != nil {
		return x.AnswerValue
	}
	return nil
}

type AnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_public_rooms_v1_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_rooms_v1_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_public_rooms_v1_dto_proto_rawDescGZIP(), []int{9}
}

func (x *AnswerResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_public_rooms_v1_dto_proto protoreflect.FileDescriptor

const file_public_rooms_v1_dto_proto_rawDesc = "" +
	"\n" +
	"\x19public/rooms/v1/dto.proto\x12\brooms.v1\x1a\x18common/types/types.proto\x1a common/types/testing_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\x1a\x19google/protobuf/any.proto\"6\n" +
	"\rRoomCandidate\x12%\n" +
	"\x0ecandidate_name\x18\x01 \x01(\tR\rcandidateName\"|\n" +
	"\x11RoomTechniqueItem\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.types.v1.TechniqueItemTypeR\x04type\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x1a\n" +
	"\bvariants\x18\x03 \x03(\tR\bvariants\"\xba\x02\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.types.v1.RoomStatusR\x06status\x12\x1f\n" +
	"\vtenant_name\x18\x03 \x01(\tR\n" +
	"tenantName\x125\n" +
	"\tcandidate\x18\x04 \x01(\v2\x17.rooms.v1.RoomCandidateR\tcandidate\x12F\n" +
	"\x10current_question\x18\x05 \x01(\v2\x1b.rooms.v1.RoomTechniqueItemR\x0fcurrentQuestion\x129\n" +
	"\x16current_question_index\x18\x06 \x01(\x05H\x00R\x14currentQuestionIndex\x88\x01\x01B\x19\n" +
	"\x17_current_question_index\"\xa0\x01\n" +
	"\vAnswerValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\" \n" +
	"\x0eGetRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetRoomResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.rooms.v1.RoomR\x04room\"\"\n" +
	"\x10StartRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x11StartRoomResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.rooms.v1.RoomR\x04room\"\x8a\x01\n" +
	"\rAnswerRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12%\n" +
	"\x0equestion_index\x18\x02 \x01(\x05R\rquestionIndex\x128\n" +
	"\fanswer_value\x18\x03 \x01(\v2\x15.rooms.v1.AnswerValueR\vanswerValue\"4\n" +
	"\x0eAnswerResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.rooms.v1.RoomR\x04roomB\x9c\x01\n" +
	"\fcom.rooms.v1B\bDtoProtoP\x01ZAgithub.com/neurochar/backend/pkg/proto_pb/public/rooms/v1;roomsv1\xa2\x02\x03RXX\xaa\x02\bRooms.V1\xca\x02\bRooms\\V1\xe2\x02\x14Rooms\\V1\\GPBMetadata\xea\x02\tRooms::V1b\x06proto3"

var (
	file_public_rooms_v1_dto_proto_rawDescOnce sync.Once
	file_public_rooms_v1_dto_proto_rawDescData []byte
)

func file_public_rooms_v1_dto_proto_rawDescGZIP() []byte {
	file_public_rooms_v1_dto_proto_rawDescOnce.Do(func() {
		file_public_rooms_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_rooms_v1_dto_proto_rawDesc), len(file_public_rooms_v1_dto_proto_rawDesc)))
	})
	return file_public_rooms_v1_dto_proto_rawDescData
}

var file_public_rooms_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_public_rooms_v1_dto_proto_goTypes = []any{
	(*RoomCandidate)(nil),        // 0: rooms.v1.RoomCandidate
	(*RoomTechniqueItem)(nil),    // 1: rooms.v1.RoomTechniqueItem
	(*Room)(nil),                 // 2: rooms.v1.Room
	(*AnswerValue)(nil),          // 3: rooms.v1.AnswerValue
	(*GetRoomRequest)(nil),       // 4: rooms.v1.GetRoomRequest
	(*GetRoomResponse)(nil),      // 5: rooms.v1.GetRoomResponse
	(*StartRoomRequest)(nil),     // 6: rooms.v1.StartRoomRequest
	(*StartRoomResponse)(nil),    // 7: rooms.v1.StartRoomResponse
	(*AnswerRequest)(nil),        // 8: rooms.v1.AnswerRequest
	(*AnswerResponse)(nil),       // 9: rooms.v1.AnswerResponse
	(types.TechniqueItemType)(0), // 10: types.v1.TechniqueItemType
	(types.RoomStatus)(0),        // 11: types.v1.RoomStatus
}
var file_public_rooms_v1_dto_proto_depIdxs = []int32{
	10, // 0: rooms.v1.RoomTechniqueItem.type:type_name -> types.v1.TechniqueItemType
	11, // 1: rooms.v1.Room.status:type_name -> types.v1.RoomStatus
	0,  // 2: rooms.v1.Room.candidate:type_name -> rooms.v1.RoomCandidate
	1,  // 3: rooms.v1.Room.current_question:type_name -> rooms.v1.RoomTechniqueItem
	2,  // 4: rooms.v1.GetRoomResponse.room:type_name -> rooms.v1.Room
	2,  // 5: rooms.v1.StartRoomResponse.room:type_name -> rooms.v1.Room
	3,  // 6: rooms.v1.AnswerRequest.answer_value:type_name -> rooms.v1.AnswerValue
	2,  // 7: rooms.v1.AnswerResponse.room:type_name -> rooms.v1.Room
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_public_rooms_v1_dto_proto_init() }
func file_public_rooms_v1_dto_proto_init() {
	if File_public_rooms_v1_dto_proto != nil {
		return
	}
	file_public_rooms_v1_dto_proto_msgTypes[2].OneofWrappers = []any{}
	file_public_rooms_v1_dto_proto_msgTypes[3].OneofWrappers = []any{
		(*AnswerValue_StringValue)(nil),
		(*AnswerValue_IntValue)(nil),
		(*AnswerValue_DoubleValue)(nil),
		(*AnswerValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_rooms_v1_dto_proto_rawDesc), len(file_public_rooms_v1_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_rooms_v1_dto_proto_goTypes,
		DependencyIndexes: file_public_rooms_v1_dto_proto_depIdxs,
		MessageInfos:      file_public_rooms_v1_dto_proto_msgTypes,
	}.Build()
	File_public_rooms_v1_dto_proto = out.File
	file_public_rooms_v1_dto_proto_goTypes = nil
	file_public_rooms_v1_dto_proto_depIdxs = nil
}
