// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: public/rooms/v1/service.proto

package roomsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomsPublicService_GetRoom_FullMethodName   = "/rooms.v1.RoomsPublicService/GetRoom"
	RoomsPublicService_StartRoom_FullMethodName = "/rooms.v1.RoomsPublicService/StartRoom"
	RoomsPublicService_Answer_FullMethodName    = "/rooms.v1.RoomsPublicService/Answer"
)

// RoomsPublicServiceClient is the client API for RoomsPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomsPublicServiceClient interface {
	// Получить комнату
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	// Начать комнату
	StartRoom(ctx context.Context, in *StartRoomRequest, opts ...grpc.CallOption) (*StartRoomResponse, error)
	// Ответить на вопрос
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
}

type roomsPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomsPublicServiceClient(cc grpc.ClientConnInterface) RoomsPublicServiceClient {
	return &roomsPublicServiceClient{cc}
}

func (c *roomsPublicServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, RoomsPublicService_GetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomsPublicServiceClient) StartRoom(ctx context.Context, in *StartRoomRequest, opts ...grpc.CallOption) (*StartRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRoomResponse)
	err := c.cc.Invoke(ctx, RoomsPublicService_StartRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomsPublicServiceClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, RoomsPublicService_Answer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomsPublicServiceServer is the server API for RoomsPublicService service.
// All implementations must embed UnimplementedRoomsPublicServiceServer
// for forward compatibility.
type RoomsPublicServiceServer interface {
	// Получить комнату
	GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error)
	// Начать комнату
	StartRoom(context.Context, *StartRoomRequest) (*StartRoomResponse, error)
	// Ответить на вопрос
	Answer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	mustEmbedUnimplementedRoomsPublicServiceServer()
}

// UnimplementedRoomsPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomsPublicServiceServer struct{}

func (UnimplementedRoomsPublicServiceServer) GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedRoomsPublicServiceServer) StartRoom(context.Context, *StartRoomRequest) (*StartRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRoom not implemented")
}
func (UnimplementedRoomsPublicServiceServer) Answer(context.Context, *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedRoomsPublicServiceServer) mustEmbedUnimplementedRoomsPublicServiceServer() {}
func (UnimplementedRoomsPublicServiceServer) testEmbeddedByValue()                            {}

// UnsafeRoomsPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomsPublicServiceServer will
// result in compilation errors.
type UnsafeRoomsPublicServiceServer interface {
	mustEmbedUnimplementedRoomsPublicServiceServer()
}

func RegisterRoomsPublicServiceServer(s grpc.ServiceRegistrar, srv RoomsPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedRoomsPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomsPublicService_ServiceDesc, srv)
}

func _RoomsPublicService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomsPublicServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomsPublicService_GetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomsPublicServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomsPublicService_StartRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomsPublicServiceServer).StartRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomsPublicService_StartRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomsPublicServiceServer).StartRoom(ctx, req.(*StartRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomsPublicService_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomsPublicServiceServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomsPublicService_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomsPublicServiceServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomsPublicService_ServiceDesc is the grpc.ServiceDesc for RoomsPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomsPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rooms.v1.RoomsPublicService",
	HandlerType: (*RoomsPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoom",
			Handler:    _RoomsPublicService_GetRoom_Handler,
		},
		{
			MethodName: "StartRoom",
			Handler:    _RoomsPublicService_StartRoom_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _RoomsPublicService_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/rooms/v1/service.proto",
}
