// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/access_claims.proto

package authv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AccessClaims with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AccessClaims) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AccessClaims with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AccessClaimsMultiError, or
// nil if none found.
func (m *AccessClaims) ValidateAll() error {
	return m.validate(true)
}

func (m *AccessClaims) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccountId

	// no validation rules for SessionId

	// no validation rules for TenantId

	// no validation rules for RoleId

	// no validation rules for Meta

	if len(errors) > 0 {
		return AccessClaimsMultiError(errors)
	}

	return nil
}

// AccessClaimsMultiError is an error wrapping multiple validation errors
// returned by AccessClaims.ValidateAll() if the designated constraints aren't met.
type AccessClaimsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccessClaimsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccessClaimsMultiError) AllErrors() []error { return m }

// AccessClaimsValidationError is the validation error returned by
// AccessClaims.Validate if the designated constraints aren't met.
type AccessClaimsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessClaimsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessClaimsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessClaimsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessClaimsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessClaimsValidationError) ErrorName() string { return "AccessClaimsValidationError" }

// Error satisfies the builtin error interface
func (e AccessClaimsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessClaims.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessClaimsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessClaimsValidationError{}
